name: algolab
description: "An open source application to help learning algorithms and other computer stuff."

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter: { sdk: flutter }
  flutter_localizations: { sdk: flutter }

  # UI
  flutter_svg: 2.2.3
  animated_text_kit: 4.3.0
  flutter_confetti: 0.5.1
  lucide_icons_flutter: 3.1.9
  google_fonts: 7.0.0
  auto_route: 11.1.0
  animated_reorderable_list: 1.3.0
  flexible_wrap: 1.0.7
  linked_scroll_controller: 0.2.0
  flutter_scroll_shadow: 1.2.6
  simple_animations: 5.2.0

  # MVC
  mobx: 2.6.0
  flutter_mobx: 2.3.0

  # Models
  freezed_annotation: 3.1.0
  json_annotation: 4.9.0
  fast_immutable_collections: 11.1.0

  # Misc
  meta: any
  collection: any
  package_info_plus: 9.0.0
  url_launcher: 6.3.2
  get_it: 9.2.0

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: 6.0.0
  auto_route_generator: 10.4.0
  build_runner: 2.10.4
  freezed: 3.2.3
  json_serializable: 6.11.2
  mobx_codegen: 2.7.5

flutter:
  uses-material-design: true
  generate: true
