name: algolab
description: "An open source application to help learning algorithms and other computer stuff."

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter: { sdk: flutter }
  flutter_localizations: { sdk: flutter }

  # UI
  flutter_svg: 2.2.2
  animated_text_kit: 4.3.0
  confetti: 0.8.0
  lucide_icons_flutter: 3.1.6
  google_fonts: 6.3.2
  auto_route: 10.2.2

  # MVC
  mobx: 2.5.0
  flutter_mobx: 2.3.0

  # Models
  freezed_annotation: 3.1.0
  json_annotation: 4.9.0
  fast_immutable_collections: 11.1.0

  # Misc
  meta: any
  collection: any

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: 6.0.0
  auto_route_generator: 10.2.6
  build_runner: 2.10.4
  freezed: 3.2.3
  json_serializable: 6.11.1
  mobx_codegen: 2.7.4

flutter:
  uses-material-design: true
  generate: true
